name: My first workflow
on: push
jobs:
  my_first_job:
    name: My first Job
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo Hello, world!
  check_directory:
    name: Checking the file check_directory
    runs-on: ubuntu-latest
    steps:
      - name: Running ls
        uses: actions/checkout@v2
        run: ls -la --color --group-directories-first
  my_npm_job:
    name: Run npm tests
    runs-on: ubuntu-latest
    steps:
      - name: Install NPM packages
        run: npm install
      - name: Running npm test
        run: npm test