name: My first workflow
on: push
jobs:
  my_first_job:
    name: My first Job
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo Hello, world!
  my_npm_job:
    name: Run npm tests
    runs-on: ubuntu-latest
    steps:
      - name: Install NPM packages
      - run: npm install
      - run: npm test